import { createFileRoute, Link } from "@tanstack/react-router";
import { FormEvent, useState } from "react";
import { ArrowRight, BrainCircuit, Search } from "lucide-react";
import { AppShell, PageHeading } from "@/components/app-shell";
import { SignalBadge } from "@/components/signal-badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { findStock, formatPrice, stocks } from "@/data/stocks";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/analyze")({ head: () => ({ meta: [
  { title: "Analyze Stock — StockSignal AI" }, { name: "description", content: "Select an NSE stock and review mock technical indicators and its ML signal." },
  { property: "og:title", content: "Analyze Stock — StockSignal AI" }, { property: "og:description", content: "Analyze mock stock indicators and predictions." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AnalyzePage });
function AnalyzePage() {
  const [query, setQuery] = useState("RELIANCE"); const [selected, setSelected] = useState(stocks[0]); const [error, setError] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); const match = findStock(query) ?? stocks.find((item) => item.companyName.toLowerCase().includes(query.toLowerCase())); if (!match) return setError("Stock not found. Try RELIANCE, TCS, or INFY."); setSelected(match); setError(""); };
  const indicators = [{ label: "RSI", value: selected.rsi.toFixed(1) }, { label: "MACD", value: `${selected.macd >= 0 ? "+" : ""}${selected.macd}` }, { label: "SMA 50", value: formatPrice(selected.sma50) }, { label: "EMA 20", value: formatPrice(selected.ema20) }, { label: "Volume", value: selected.volume }];
  return <AppShell><PageHeading title="Analyze Stock" subtitle="Select a stock to view its mock machine-learning prediction" /><form onSubmit={submit} className="flex max-w-2xl flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input className="h-10 pl-9" list="stock-options" placeholder="Search stock name or symbol" value={query} onChange={(e) => setQuery(e.target.value)} /><datalist id="stock-options">{stocks.map((item) => <option key={item.symbol} value={item.symbol}>{item.companyName}</option>)}</datalist></div><Button type="submit" className="h-10">Analyze</Button></form>{error && <p className="mt-2 text-sm text-destructive">{error}</p>}<section className="mt-8 grid gap-5 lg:grid-cols-[1fr_320px]"><Card className="shadow-sm"><CardHeader><CardTitle>{selected.companyName.toUpperCase()}</CardTitle><p className="text-sm text-muted-foreground">NSE: {selected.symbol}</p></CardHeader><CardContent><div className="grid gap-5 sm:grid-cols-2"><div><p className="text-sm text-muted-foreground">Current Price</p><p className="mt-1 text-3xl font-bold">{formatPrice(selected.currentPrice)}</p></div><div><p className="text-sm text-muted-foreground">Change</p><p className={cn("mt-1 text-2xl font-bold", selected.changePercent >= 0 ? "text-buy" : "text-sell")}>{selected.changePercent >= 0 ? "+" : ""}{selected.changePercent.toFixed(2)}%</p></div></div></CardContent></Card><Card className="border-primary/20 bg-primary/5 shadow-sm"><CardContent className="p-6"><div className="flex items-center gap-2 text-sm font-semibold text-primary"><BrainCircuit className="size-4" /> AI Signal</div><SignalBadge signal={selected.signal} className="mt-4 min-w-24 py-1.5 text-lg" /><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-muted-foreground">Confidence</dt><dd className="mt-1 font-semibold">{selected.confidence}%</dd></div><div><dt className="text-muted-foreground">Model</dt><dd className="mt-1 font-semibold">Random Forest</dd></div></dl></CardContent></Card></section><section className="mt-8"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold">Technical Indicators</h2><Button variant="ghost" size="sm" asChild><Link to="/stock/$symbol" params={{ symbol: selected.symbol }}>Full details <ArrowRight /></Link></Button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{indicators.map((item) => <Card key={item.label} className="shadow-sm"><CardContent className="p-5"><p className="text-sm text-muted-foreground">{item.label}</p><p className="mt-2 text-xl font-semibold">{item.value}</p></CardContent></Card>)}</div></section></AppShell>;
}