import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, BarChart3, ExternalLink, Plus, Trash2 } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { SignalBadge } from "@/components/signal-badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { findStock, formatPrice } from "@/data/stocks";
import { useWatchlist } from "@/lib/mock-storage";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/stock/$symbol")({ head: ({ params }) => { const item = findStock(params.symbol); const name = item?.companyName ?? "Stock"; return { meta: [
  { title: `${name} — StockSignal AI` }, { name: "description", content: `View mock indicators and the ML prediction for ${name}.` },
  { property: "og:title", content: `${name} — StockSignal AI` }, { property: "og:description", content: `Educational stock signal details for ${name}.` },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }; }, component: StockDetailsPage });
function StockDetailsPage() {
  const { symbol } = Route.useParams(); const item = findStock(symbol); const [watchlist, setWatchlist] = useWatchlist();
  if (!item) return <AppShell><div className="py-20 text-center"><h1 className="text-2xl font-bold">Stock not found</h1><p className="mt-2 text-muted-foreground">This symbol is not in the mock dataset.</p><Button className="mt-6" asChild><Link to="/top-signals"><ArrowLeft /> View all stocks</Link></Button></div></AppShell>;
  const isWatched = watchlist.includes(item.symbol); const rows = [{ indicator: "RSI", value: item.rsi.toFixed(1), status: item.rsi >= 55 ? "Bullish" : item.rsi < 45 ? "Bearish" : "Neutral" }, { indicator: "MACD", value: `${item.macd >= 0 ? "+" : ""}${item.macd}`, status: item.macd >= 0 ? "Bullish" : "Bearish" }, { indicator: "SMA 50", value: formatPrice(item.sma50), status: item.currentPrice >= item.sma50 ? "Price Above" : "Price Below" }, { indicator: "EMA 20", value: formatPrice(item.ema20), status: item.currentPrice >= item.ema20 ? "Price Above" : "Price Below" }, { indicator: "Volume", value: item.volume, status: "Normal" }];
  return <AppShell><Button variant="ghost" size="sm" className="mb-5" asChild><Link to="/top-signals"><ArrowLeft /> Back to signals</Link></Button><div className="flex flex-col gap-5 border-b pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">NSE: {item.symbol}</p><h1 className="mt-1 text-3xl font-bold">{item.companyName}</h1><div className="mt-5 flex items-baseline gap-4"><span className="text-3xl font-bold">{formatPrice(item.currentPrice)}</span><span className={cn("font-semibold", item.changePercent >= 0 ? "text-buy" : "text-sell")}>{item.changePercent >= 0 ? "+" : ""}{item.changePercent.toFixed(2)}%</span></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setWatchlist((current) => isWatched ? current.filter((value) => value !== item.symbol) : [...current, item.symbol])}>{isWatched ? <Trash2 /> : <Plus />}{isWatched ? "Remove from Watchlist" : "Add to Watchlist"}</Button><Button asChild><a href={item.tradingViewUrl} target="_blank" rel="noreferrer">View Price Chart <ExternalLink /></a></Button></div></div><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_320px]"><section><h2 className="mb-4 text-lg font-semibold">Technical Indicators</h2><div className="overflow-hidden rounded-lg border bg-card"><Table><TableHeader className="bg-muted/50"><TableRow><TableHead className="pl-5">Indicator</TableHead><TableHead>Value</TableHead><TableHead className="pr-5">Status</TableHead></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.indicator}><TableCell className="pl-5 font-medium">{row.indicator}</TableCell><TableCell>{row.value}</TableCell><TableCell className="pr-5 text-muted-foreground">{row.status}</TableCell></TableRow>)}</TableBody></Table></div></section><section><h2 className="mb-4 text-lg font-semibold">AI Prediction</h2><Card className="border-primary/20 bg-primary/5 shadow-sm"><CardContent className="p-6"><div className="mb-5 flex size-10 items-center justify-center rounded-md bg-primary/10 text-primary"><BarChart3 /></div><SignalBadge signal={item.signal} className="min-w-28 py-2 text-xl" /><div className="mt-6 space-y-4"><div><p className="text-sm text-muted-foreground">Confidence</p><p className="mt-1 text-2xl font-bold">{item.confidence}%</p></div><div><p className="text-sm text-muted-foreground">Model</p><p className="mt-1 font-semibold">Random Forest</p></div></div></CardContent></Card></section></div></AppShell>;
}